Algoritmo "somandoSequencia02"

Var
c,n,soma:inteiro

Inicio
   c <- 500
   n <- 0
   EscrevaL("-------------------------------")
   EscrevaL("     Somando em sequencia      ")
   EscrevaL("-------------------------------")
   Enquanto c >= n faca
   Escreva(" +",c)
   c <- c-50
   soma <- c + soma
   FimEnquanto
   EscrevaL("")
   EscrevaL("-------------------------------")
   Escreva("Resultado da soma:",soma)
Fimalgoritmo