Algoritmo "COMBINACOES"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 03/07/2024
Var
// Seção de Declarações das variáveis 
     C1,C2:Inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
     Para C1 := 1 ate 3 faca
          Para C2 := 1 ate 3 faca
               EscrevaL (C1,C2)
          FimPara
     FimPara

Fimalgoritmo