Algoritmo "contarAte20"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 17/06/2024
Var
// Seção de Declarações das variáveis 

   contador:inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
     contador <- 0
     Enquanto (contador <=20) faca
              Escreval (contador)
              contador <- contador + 1
     FimEnquanto
     Escreval ("Terminei de contar")


Fimalgoritmo