Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 01/05/2024
Var
// Seção de Declarações das variáveis 
   reais,dolares:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   Escreva("Quantos reais eu tenho?R$")
   Leia(reais)
   dolares<-reais/5.20
   Escreval("Então eu posso ter US$",dolares)
   
   
Fimalgoritmo