Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/05/2024
Var
// Seção de Declarações das variáveis 

          preco,imposto:Real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

          Escreva("Qaul o valor do produto?US$")
          Leia (preco)
          imposto<-(preco*60)/100
          Escreva("O valor do imposto será de US$",imposto:5:2)
Fimalgoritmo